CXX = x86_64-w64-mingw32-g++
CXXFLAGS = -Wall -Wextra -std=c++14 -Iinclude -static-libgcc -static-libstdc++
SRCDIR = src
SOURCES = $(wildcard $(SRCDIR)/*.cpp)
OBJECTS = $(SOURCES:.cpp=.win.o)
TARGET = inventario.exe

$(TARGET): $(OBJECTS)
	$(CXX) $(OBJECTS) -o $(TARGET)

%.win.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(SRCDIR)/*.win.o $(TARGET)

.PHONY: clean