CXX = g++
CXXFLAGS = -Wall -Wextra -std=c++14 -Iinclude
SRCDIR = src
SOURCES = $(wildcard $(SRCDIR)/*.cpp)
OBJECTS = $(SOURCES:.cpp=.o)
TARGET = academia.exe

$(TARGET): $(OBJECTS)
	$(CXX) $(OBJECTS) -o $(TARGET)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	del /Q $(SRCDIR)\*.o $(TARGET) 2>nul || echo.

.PHONY: clean